spring.application.name=ticketmaster-user-service
# 1. Server Portu
server.port=8081

# 2. Database Qo?ulmas? (PostgreSQL üçün)
spring.datasource.url=jdbc:postgresql://ticketmaster-postgres:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

# 3. JWT T?nziml?m?l?ri (MÜTL?QD?R!)
# Bu açar ?n az? 64 simvoldan ibar?t random kod olmal?d?r
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# 4. Eureka Client (?g?r Eureka-n? h?l? ba?latmam?sansa, bu hiss? x?ta ver? bil?r, amma qals?n)
eureka.client.service-url.defaultZone=http://ticketmaster-eureka:8761/eureka/
