spring.application.name=ticketmaster-ticket-service
server.port=8085

# Database - Docker daxilind? servis ad? il? müraci?t edirik
# Port Docker daxilind? 5432-dir!
spring.datasource.url=jdbc:postgresql://ticketmaster-postgres:5432/ticket_db
spring.datasource.username=postgres
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis - Docker daxili ünvan
spring.data.redis.host=ticketmaster-redis
spring.data.redis.port=6379

# Eureka - Docker daxili ünvan
eureka.client.service-url.defaultZone=http://ticketmaster-eureka:8761/eureka/
eureka.instance.prefer-ip-address=true

# Kafka - ?N VAC?B H?SS? ?
# Docker daxili portu 29092-dir
spring.kafka.bootstrap-servers=ticketmaster-kafka:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=ticket-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Resilience4j (Oldu?u kimi qal?r)
resilience4j.circuitbreaker.instances.eventService.sliding-window-size=10
resilience4j.circuitbreaker.instances.eventService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.sliding-window-size=10