spring.application.name=ticketmaster-event-service
server.port=8082

# Baza ünvan? (Docker daxili ad? v? portu il?)
spring.datasource.url=jdbc:postgresql://ticketmaster-postgres:5432/Ticketmaster
spring.datasource.username=postgres
spring.datasource.password=

# Kafka ünvan? - S?nin docker-compose-da daxili port 29092-dir! ?
spring.kafka.bootstrap-servers=ticketmaster-kafka:29092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Redis ünvan?
spring.data.redis.host=ticketmaster-redis
spring.data.redis.port=6379

# Eureka - S?nin docker-compose-da ad? 'ticketmaster-eureka' deyilse, 'eureka-server' ola biler
eureka.client.service-url.defaultZone=http://ticketmaster-eureka:8761/eureka/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Eureka-ya ID ?v?zin? IP il? qeydiyyatdan keçm?sini deyirik
eureka.instance.prefer-ip-address=true